# Generated by Django 5.1.3 on 2024-11-27 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="city",
            field=models.CharField(
                choices=[
                    ("CHN", "Chennai"),
                    ("TRI", "Tiruchirappalli"),
                    ("CBE", "Coimbatore"),
                ],
                default="CHN",
                max_length=3,
            ),
        ),
    ]
