# Generated by Django 5.1.3 on 2024-11-27 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_customuser_city"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="city",
            field=models.CharField(
                blank=True,
                choices=[
                    ("CHN", "Chennai"),
                    ("TRI", "Tiruchirappalli"),
                    ("CBE", "Coimbatore"),
                ],
                default="CHN",
                max_length=3,
                null=True,
            ),
        ),
    ]
